version: "3.9"

services:
  percona:
    image: ${PERCONA_IMAGE}
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-file /init.sql
    hostname: "percona-{{.Node.Hostname}}"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - localserver
    volumes:
      - ./var/storage/percona:/var/lib/mysql:rw
      - ./config/storage/percona/conf.d:/etc/my.cnf.d:ro
      - ./config/storage/percona/init.sql:/init.sql:ro

networks:
  localserver:
    external: true